apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: {{ .Values.appName }}
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - image: bdsaisantosh/twitter-server:latest
          imagePullPolicy: Always
          name: {{ .Values.appName }}
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          ports:
          - containerPort: 5000